/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

/**
 *
 * @author Cauã
 */
public class ElaborarEstimativaView extends javax.swing.JFrame {

    /**
     * Creates new form ElaborarEstimativaView
     */
    public ElaborarEstimativaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstimativaProjeto = new javax.swing.JTable();
        lblWeb = new javax.swing.JLabel();
        lblIOS = new javax.swing.JLabel();
        lblAndroid = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        chcWeb = new javax.swing.JCheckBox();
        chcIOS = new javax.swing.JCheckBox();
        chcAndroid = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPrecosPorDiaTrabalho = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblValoresFinais = new javax.swing.JTable();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEstimativaProjeto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblEstimativaProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblEstimativaProjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Pequeno", "                     10", "                     10", "                     10", null, null},
                {null, "Médio", "                     30", "                     30", "                     30", null, null},
                {null, "Grande", "                     50", "                     50", "                     50", null, null},
                {null, "MVP", "                     30%", "                     30%", "                     30%", null, null},
                {null, "Básico", "                     50%", "                     50%", "                     50%", null, null},
                {null, "Profissional", "                     70%", "                     70%", "                     70%", null, null},
                {null, "Cadastro por E-mail e Senha", "                     1                     ", "                     1", "                     1", null, null},
                {null, "Cadastro pelo Facebook", "                     2                     ", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Twitter", "                     2", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Google", "                     2", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Linkedln", "                     2", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Github", "                     2", "                     2", "                     2", null, null},
                {null, "E-mails de Convite de Usuário", "                     2", "                     ---", "                     ---", null, null},
                {null, "Contas Multi-tenant", "                     3", "                     ---", "                     ---", null, null},
                {null, "Subdomínios", "                     4", "                     ---", "                     ---", null, null},
                {null, "Domínios Personalizados", "                     4", "                     ---", "                     ---", null, null},
                {null, "Painel (Dashboard)", "                     5", "                     5", "                     5", null, null},
                {null, "Feed de Atividades (Activity Feed)", "                     4", "                     4", "                     4", null, null},
                {null, "Upload de Arquivos (File Uploading)", "                     4", "                     ---", "                     ---", null, null},
                {null, "Upload de Mídia (Media Uploading", "                     ---", "                     4", "                     4", null, null},
                {null, "Perfis de Usuário (User Profiles)", "                     2", "                     2", "                     2", null, null},
                {null, "E-mails Transacionais (Transactional Emails)", "                     2", "                     ---", "                     ---", null, null},
                {null, "Tags", "                     2", "                     2", "                     2", null, null},
                {null, "Avaliações ou Comentários (Rating or Reviews)", "                     5", "                     5", "                     5", null, null},
                {null, "Processamento de Áudio/Vídeo)", "                     5", "                     ---", "                     ---", null, null},
                {null, "Pesquisa de Texto Livre (Free text searching)", "                     5", "                     ---", "                     ---", null, null},
                {null, "Pesquisa (Searching)", "                     ---", "                     3", "                     3", null, null},
                {null, "Calendário (Calendaring)", "                     7", "                     6", "                     6", null, null},
                {null, "Exibição de Dados de Mapa / Geolocalização", "                     3", "                     3", "                     3", null, null},
                {null, "Exibição de Marcadores/Regiões de Mapa Personalizados", "                     3", "                     3", "                     3", null, null},
                {null, "Reservas (Bookings)", "                     8", "                     5", "                     5", null, null},
                {null, "Mensagens (Messaging)", "                     6", "                     5", "                     5", null, null},
                {null, "Fóruns ou Comentários", "                     5", "                     5", "                     5", null, null},
                {null, "Compartilhamento Social (Social Sharing)", "                     2", "                     1", "                     1", null, null},
                {null, "Integração com Facebook Open Graph (Push to Facebook Open Graph)", "                     5", "                     3", "                     3", null, null},
                { new Boolean(false), "Notificações Push (Push Notifications)", "                     ---", "                     3", "                     3", null, null},
                {null, "Planos de Assinatura (Subscription plans)", "                     8", "                     ---", "                     ---", null, null},
                {null, "Processamento de Pagamentos (Payment processing)", "                     5", "                     5", "                     5", null, null},
                {null, "Carrinho de Compras (Shopping Cart)", "                     8", "                     5", "                     5", null, null},
                {null, "Marketplace de Usuários (User Marketplace)", "                     12", "                     ---", "                     ---", null, null},
                {null, "Gerenciamento de Produtos (Product Management)", "                     4", "                     ---", "                     ---", null, null},
                {null, "Compras dentro do Aplicativo (In-App Purchasing)", "                     ---", "                     5", "                     5", null, null},
                {null, "Coleta de Informações de Pagamento", "                     ---", "                     3", "                     3", null, null},
                {null, "Integração com CMS (CMS Integration)", "                     7", "                     ---", "                     ---", null, null},
                {null, "Páginas de Administração de Usuários (User Admin pages)", "                     3", "                     ---", "                     ---", null, null},
                {null, "Moderação / Aprovação de Conteúdo (Moderation / Content Approval)", "                     4", "                     ---", "                     ---", null, null},
                {null, "Intercom", "                     3", "                     3", "                     3", null, null},
                {null, "Análises de Uso (Usage Analytics)", "                     3", "                     3", "                     3", null, null},
                {null, "Relatório de Erros (Crash Reporting)", "                     0", "                     1", "                     1", null, null},
                {null, "Monitoramento de Performance (Performance Monitoring)", "                     1", "                     ---", "                     ---", null, null},
                {null, "Suporte Multilíngue (Multilingual Support)", "                     4", "                     4", "                     4", null, null},
                {null, "Conectar a um ou mais serviços de terceiros", "                     6", "                     3", "                     3", null, null},
                {null, "Uma API para que terceiros integrem ao seu app", "                     8", "                     ---", "                     ---", null, null},
                {null, "Envio de SMS (SMS Messaging)", "                     4", "                     4", "                     4", null, null},
                {null, "Mascaramento de Número de Telefone (Phone Number Masking)", "                     4", "                     4", "                     4", null, null},
                {null, "Segurança baseada em Certificado SSL", "                     3", "                     ---", "                     ---", null, null},
                {null, "Proteção contra DoS (DoS protection)", "                     5", "                     ---", "                     ---", null, null},
                {null, "Autenticação em Duas Etapas (Two Factor Authentication)", "                     5", "                     5", "                     5", null, null},
                {null, "Desenvolvimento Específico do Aplicativo", "                     0", "                     0", "                     0", null, null},
                {null, "Design de Ícone do App (App Icon Design)", "                     ---", "                     7", "                     7", null, null},
                {null, "Sincronização em Nuvem (Cloud Syncing)", "                     ---", "                     5", "                     5", null, null},
                {null, "Dados de Sensores do Dispositivo (Device Sensor Data)", "                     ---", "                     5", "                     5", null, null},
                {null, "Códigos de Barras ou QR Codes (Barcodes ou QR Codes)", "                     ---", "                     2", "                     2", null, null},
                {null, "Dados de Saúde (Health Data)", "                     ---", "                     4", "                     ---", null, null},
                {null, "Apple Watch", "                     ---", "                     7", "                     ---", null, null},
                {null, "Gerente de Projeto (Project Manager)", "                     10", "                     10", "                     10", null, null}
            },
            new String [] {
                "", "Funcionalidade que o aplicativo terá", "Dias (ou %)", "Dias (ou %)", "Dias (ou %)", "Total de dias", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstimativaProjeto.setToolTipText("");
        tblEstimativaProjeto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblEstimativaProjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEstimativaProjeto.setRowHeight(50);
        tblEstimativaProjeto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEstimativaProjeto.setShowHorizontalLines(true);
        tblEstimativaProjeto.setShowVerticalLines(true);
        tblEstimativaProjeto.setSurrendersFocusOnKeystroke(true);
        tblEstimativaProjeto.getTableHeader().setResizingAllowed(false);
        tblEstimativaProjeto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEstimativaProjeto);
        if (tblEstimativaProjeto.getColumnModel().getColumnCount() > 0) {
            tblEstimativaProjeto.getColumnModel().getColumn(0).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblEstimativaProjeto.getColumnModel().getColumn(1).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(1).setPreferredWidth(350);
            tblEstimativaProjeto.getColumnModel().getColumn(2).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(3).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(4).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(5).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(6).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(6).setPreferredWidth(18);
        }

        lblWeb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblWeb.setText("WEB E BACK-END");

        lblIOS.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblIOS.setText("iOS");

        lblAndroid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblAndroid.setText("ANDROID");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblPrecosPorDiaTrabalho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblPrecosPorDiaTrabalho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPrecosPorDiaTrabalho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Preço por dia de traballho  -Designer UI/UX", null, null, null},
                {null, "Preço por dia de traballho - Gerência de Projeto", null, null, null},
                {null, "Preço por dia de traballho  - Desenvolvimento", null, null, null},
                {null, "Custo com hardware e instalações físicas.", null, null, null},
                {null, "Custo com softwares.", null, null, null},
                {null, "Custo com riscos.", null, null, null},
                {null, "Custo com garantia.", null, null, null},
                {null, "Fundo de reserva", null, null, null},
                {null, "Outros custos.", null, null, ""},
                {null, "Percentual com impostos(%)", null, "                     ---", "                     ---"},
                {null, "Percentual de Lucro desejado (%)", null, "                     ---", "                     ---"}
            },
            new String [] {
                "", "Taxas extras", "Valor", "Valor", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrecosPorDiaTrabalho.setRowHeight(50);
        tblPrecosPorDiaTrabalho.setShowHorizontalLines(true);
        tblPrecosPorDiaTrabalho.setShowVerticalLines(true);
        tblPrecosPorDiaTrabalho.getTableHeader().setResizingAllowed(false);
        tblPrecosPorDiaTrabalho.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblPrecosPorDiaTrabalho);
        if (tblPrecosPorDiaTrabalho.getColumnModel().getColumnCount() > 0) {
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(0).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(0).setPreferredWidth(18);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(1).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(1).setPreferredWidth(355);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(2).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(3).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Criar Estimativa");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ELABORAR ESTIMATIVA DE PROJETO");

        tblValoresFinais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblValoresFinais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblValoresFinais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Valor", null},
                {"+ Taxas Extras", null},
                {"Imposto  Calculado", null},
                {"+ Impostos", null},
                {"Lucro Calculado", null},
                {"Dias", null},
                {"Meses", null},
                {"Preço Final ao Cliente", null},
                {"Média por Mês", null}
            },
            new String [] {
                "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblValoresFinais.setRowHeight(50);
        tblValoresFinais.setShowHorizontalLines(true);
        tblValoresFinais.setShowVerticalLines(true);
        tblValoresFinais.getTableHeader().setResizingAllowed(false);
        tblValoresFinais.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblValoresFinais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(683, 683, 683)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(chcWeb)
                                        .addGap(88, 88, 88))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblWeb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIOS)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(chcIOS)))
                                .addGap(87, 87, 87)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(chcAndroid))
                                    .addComponent(lblAndroid))
                                .addGap(55, 55, 55)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(317, 317, 317))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(336, 336, 336))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(365, 365, 365))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(647, 647, 647)
                        .addComponent(jLabel1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWeb)
                        .addGap(6, 6, 6)
                        .addComponent(chcWeb))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIOS)
                        .addGap(6, 6, 6)
                        .addComponent(chcIOS))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAndroid)
                        .addGap(6, 6, 6)
                        .addComponent(chcAndroid))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElaborarEstimativaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chcAndroid;
    private javax.swing.JCheckBox chcIOS;
    private javax.swing.JCheckBox chcWeb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblAndroid;
    private javax.swing.JLabel lblIOS;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JTable tblEstimativaProjeto;
    private javax.swing.JTable tblPrecosPorDiaTrabalho;
    private javax.swing.JTable tblValoresFinais;
    // End of variables declaration//GEN-END:variables
}
