/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Cauã
 */
public class ElaborarEstimativaView extends javax.swing.JFrame {

    /**
     * Creates new form ElaborarEstimativaView
     */
    public ElaborarEstimativaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstimativaProjeto = new javax.swing.JTable();
        lblWeb = new javax.swing.JLabel();
        lblIOS = new javax.swing.JLabel();
        lblAndroid = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        chcWeb = new javax.swing.JCheckBox();
        chcIOS = new javax.swing.JCheckBox();
        chcAndroid = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPrecosPorDiaTrabalho = new javax.swing.JTable();
        btnCriarEstimativa = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblValoresFinais = new javax.swing.JTable();
        lblNomeProjeto = new javax.swing.JLabel();
        txtNomeProjeto = new javax.swing.JTextField();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tblEstimativaProjeto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblEstimativaProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblEstimativaProjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Pequeno", "                     10", "                     10", "                     10", null, null},
                {null, "Médio", "                     30", "                     30", "                     30", null, null},
                {null, "Grande", "                     50", "                     50", "                     50", null, null},
                {null, "MVP", "                     30%", "                     30%", "                     30%", null, null},
                {null, "Básico", "                     50%", "                     50%", "                     50%", null, null},
                {null, "Profissional", "                     70%", "                     70%", "                     70%", null, null},
                {null, "Cadastro por E-mail e Senha", "                     1                     ", "                     1", "                     1", null, null},
                {null, "Cadastro pelo Facebook", "                     2                     ", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Twitter", "                     2", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Google", "                     2", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Linkedln", "                     2", "                     2", "                     2", null, null},
                {null, "Cadastro pelo Github", "                     2", "                     2", "                     2", null, null},
                {null, "E-mails de Convite de Usuário", "                     2", "                     ---", "                     ---", null, null},
                {null, "Contas Multi-tenant", "                     3", "                     ---", "                     ---", null, null},
                {null, "Subdomínios", "                     4", "                     ---", "                     ---", null, null},
                {null, "Domínios Personalizados", "                     4", "                     ---", "                     ---", null, null},
                {null, "Painel (Dashboard)", "                     5", "                     5", "                     5", null, null},
                {null, "Feed de Atividades (Activity Feed)", "                     4", "                     4", "                     4", null, null},
                {null, "Upload de Arquivos (File Uploading)", "                     4", "                     ---", "                     ---", null, null},
                {null, "Upload de Mídia (Media Uploading", "                     ---", "                     4", "                     4", null, null},
                {null, "Perfis de Usuário (User Profiles)", "                     2", "                     2", "                     2", null, null},
                {null, "E-mails Transacionais (Transactional Emails)", "                     2", "                     ---", "                     ---", null, null},
                {null, "Tags", "                     2", "                     2", "                     2", null, null},
                {null, "Avaliações ou Comentários (Rating or Reviews)", "                     5", "                     5", "                     5", null, null},
                {null, "Processamento de Áudio/Vídeo)", "                     5", "                     ---", "                     ---", null, null},
                {null, "Pesquisa de Texto Livre (Free text searching)", "                     5", "                     ---", "                     ---", null, null},
                {null, "Pesquisa (Searching)", "                     ---", "                     3", "                     3", null, null},
                {null, "Calendário (Calendaring)", "                     7", "                     6", "                     6", null, null},
                {null, "Exibição de Dados de Mapa / Geolocalização", "                     3", "                     3", "                     3", null, null},
                {null, "Exibição de Marcadores/Regiões de Mapa Personalizados", "                     3", "                     3", "                     3", null, null},
                {null, "Reservas (Bookings)", "                     8", "                     5", "                     5", null, null},
                {null, "Mensagens (Messaging)", "                     6", "                     5", "                     5", null, null},
                {null, "Fóruns ou Comentários", "                     5", "                     5", "                     5", null, null},
                {null, "Compartilhamento Social (Social Sharing)", "                     2", "                     1", "                     1", null, null},
                {null, "Integração com Facebook Open Graph (Push to Facebook Open Graph)", "                     5", "                     3", "                     3", null, null},
                { new Boolean(false), "Notificações Push (Push Notifications)", "                     ---", "                     3", "                     3", null, null},
                {null, "Planos de Assinatura (Subscription plans)", "                     8", "                     ---", "                     ---", null, null},
                {null, "Processamento de Pagamentos (Payment processing)", "                     5", "                     5", "                     5", null, null},
                {null, "Carrinho de Compras (Shopping Cart)", "                     8", "                     5", "                     5", null, null},
                {null, "Marketplace de Usuários (User Marketplace)", "                     12", "                     ---", "                     ---", null, null},
                {null, "Gerenciamento de Produtos (Product Management)", "                     4", "                     ---", "                     ---", null, null},
                {null, "Compras dentro do Aplicativo (In-App Purchasing)", "                     ---", "                     5", "                     5", null, null},
                {null, "Coleta de Informações de Pagamento", "                     ---", "                     3", "                     3", null, null},
                {null, "Integração com CMS (CMS Integration)", "                     7", "                     ---", "                     ---", null, null},
                {null, "Páginas de Administração de Usuários (User Admin pages)", "                     3", "                     ---", "                     ---", null, null},
                {null, "Moderação / Aprovação de Conteúdo (Moderation / Content Approval)", "                     4", "                     ---", "                     ---", null, null},
                {null, "Intercom", "                     3", "                     3", "                     3", null, null},
                {null, "Análises de Uso (Usage Analytics)", "                     3", "                     3", "                     3", null, null},
                {null, "Relatório de Erros (Crash Reporting)", "                     0", "                     1", "                     1", null, null},
                {null, "Monitoramento de Performance (Performance Monitoring)", "                     1", "                     ---", "                     ---", null, null},
                {null, "Suporte Multilíngue (Multilingual Support)", "                     4", "                     4", "                     4", null, null},
                {null, "Conectar a um ou mais serviços de terceiros", "                     6", "                     3", "                     3", null, null},
                {null, "Uma API para que terceiros integrem ao seu app", "                     8", "                     ---", "                     ---", null, null},
                {null, "Envio de SMS (SMS Messaging)", "                     4", "                     4", "                     4", null, null},
                {null, "Mascaramento de Número de Telefone (Phone Number Masking)", "                     4", "                     4", "                     4", null, null},
                {null, "Segurança baseada em Certificado SSL", "                     3", "                     ---", "                     ---", null, null},
                {null, "Proteção contra DoS (DoS protection)", "                     5", "                     ---", "                     ---", null, null},
                {null, "Autenticação em Duas Etapas (Two Factor Authentication)", "                     5", "                     5", "                     5", null, null},
                {null, "Desenvolvimento Específico do Aplicativo", "                     0", "                     0", "                     0", null, null},
                {null, "Design de Ícone do App (App Icon Design)", "                     ---", "                     7", "                     7", null, null},
                {null, "Sincronização em Nuvem (Cloud Syncing)", "                     ---", "                     5", "                     5", null, null},
                {null, "Dados de Sensores do Dispositivo (Device Sensor Data)", "                     ---", "                     5", "                     5", null, null},
                {null, "Códigos de Barras ou QR Codes (Barcodes ou QR Codes)", "                     ---", "                     2", "                     2", null, null},
                {null, "Dados de Saúde (Health Data)", "                     ---", "                     4", "                     ---", null, null},
                {null, "Apple Watch", "                     ---", "                     7", "                     ---", null, null},
                {null, "Gerente de Projeto (Project Manager)", "                     10", "                     10", "                     10", null, null}
            },
            new String [] {
                "", "Funcionalidade que o aplicativo terá", "Dias(ou %)", "Dias (ou %)", "Dias (ou %)", "Total de dias", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstimativaProjeto.setToolTipText("");
        tblEstimativaProjeto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblEstimativaProjeto.setColumnSelectionAllowed(true);
        tblEstimativaProjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEstimativaProjeto.setRowHeight(50);
        tblEstimativaProjeto.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblEstimativaProjeto.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblEstimativaProjeto.setShowGrid(true);
        tblEstimativaProjeto.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tblEstimativaProjeto);
        if (tblEstimativaProjeto.getColumnModel().getColumnCount() > 0) {
            tblEstimativaProjeto.getColumnModel().getColumn(0).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblEstimativaProjeto.getColumnModel().getColumn(1).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(1).setPreferredWidth(350);
            tblEstimativaProjeto.getColumnModel().getColumn(2).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(3).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(4).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(5).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(6).setResizable(false);
            tblEstimativaProjeto.getColumnModel().getColumn(6).setPreferredWidth(18);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 54;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1537;
        gridBagConstraints.ipady = 405;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 40);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        lblWeb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblWeb.setText("WEB E BACK-END");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 7, 15, 0);
        getContentPane().add(lblWeb, gridBagConstraints);

        lblIOS.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblIOS.setText("iOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 21, 0, 0);
        getContentPane().add(lblIOS, gridBagConstraints);

        lblAndroid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblAndroid.setText("ANDROID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        getContentPane().add(lblAndroid, gridBagConstraints);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jSeparator3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 77, 0, 0);
        getContentPane().add(chcWeb, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 25, 0, 0);
        getContentPane().add(chcIOS, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 40, 0, 0);
        getContentPane().add(chcAndroid, gridBagConstraints);

        tblPrecosPorDiaTrabalho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblPrecosPorDiaTrabalho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPrecosPorDiaTrabalho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Preço por dia de traballho  -Designer UI/UX", null, null, null},
                {null, "Preço por dia de traballho - Gerência de Projeto", null, null, null},
                {null, "Preço por dia de traballho  - Desenvolvimento", null, null, null},
                {null, "Custo com hardware e instalações físicas.", null, null, null},
                {null, "Custo com softwares.", null, null, null},
                {null, "Custo com riscos.", null, null, null},
                {null, "Custo com garantia.", null, null, null},
                {null, "Fundo de reserva", null, null, null},
                {null, "Outros custos.", null, null, ""},
                {null, "Percentual com impostos(%)", null, "                     ---", "                     ---"},
                {null, "Percentual de Lucro desejado (%)", null, "                     ---", "                     ---"}
            },
            new String [] {
                "", "Taxas extras", "Valor", "Valor", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrecosPorDiaTrabalho.setRowHeight(50);
        tblPrecosPorDiaTrabalho.setShowHorizontalLines(true);
        tblPrecosPorDiaTrabalho.setShowVerticalLines(true);
        tblPrecosPorDiaTrabalho.getTableHeader().setResizingAllowed(false);
        tblPrecosPorDiaTrabalho.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblPrecosPorDiaTrabalho);
        if (tblPrecosPorDiaTrabalho.getColumnModel().getColumnCount() > 0) {
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(0).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(0).setPreferredWidth(18);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(1).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(1).setPreferredWidth(355);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(2).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(3).setResizable(false);
            tblPrecosPorDiaTrabalho.getColumnModel().getColumn(4).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 488;
        gridBagConstraints.ipady = 145;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        btnCriarEstimativa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriarEstimativa.setText("Criar Estimativa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 0, 0);
        getContentPane().add(btnCriarEstimativa, gridBagConstraints);

        tblValoresFinais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblValoresFinais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblValoresFinais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Valor", null},
                {"+ Taxas Extras", null},
                {"Imposto  Calculado", null},
                {"+ Impostos", null},
                {"Lucro Calculado", null},
                {"Dias", null},
                {"Meses", null},
                {"Preço Final ao Cliente", null},
                {"Média por Mês", null}
            },
            new String [] {
                "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblValoresFinais.setRowHeight(50);
        tblValoresFinais.setShowHorizontalLines(true);
        tblValoresFinais.setShowVerticalLines(true);
        tblValoresFinais.getTableHeader().setResizingAllowed(false);
        tblValoresFinais.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblValoresFinais);
        if (tblValoresFinais.getColumnModel().getColumnCount() > 0) {
            tblValoresFinais.getColumnModel().getColumn(0).setResizable(false);
            tblValoresFinais.getColumnModel().getColumn(1).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 18, 0, 40);
        getContentPane().add(jScrollPane4, gridBagConstraints);

        lblNomeProjeto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNomeProjeto.setText("Nome do Projeto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 40, 0, 0);
        getContentPane().add(lblNomeProjeto, gridBagConstraints);

        txtNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        getContentPane().add(txtNomeProjeto, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElaborarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElaborarEstimativaView().setVisible(true);
            }
        });
    }

    public JButton getBtnCriarEstimativa() {
        return btnCriarEstimativa;
    }

    public JCheckBox getChcAndroid() {
        return chcAndroid;
    }

    public JCheckBox getChcIOS() {
        return chcIOS;
    }

    public JCheckBox getChcWeb() {
        return chcWeb;
    }

    public JTable getTblEstimativaProjeto() {
        return tblEstimativaProjeto;
    }

    public JTable getTblPrecosPorDiaTrabalho() {
        return tblPrecosPorDiaTrabalho;
    }

    public JTable getTblValoresFinais() {
        return tblValoresFinais;
    }

    public JTextField getTxtNomeProjeto() {
        return txtNomeProjeto;
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarEstimativa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chcAndroid;
    private javax.swing.JCheckBox chcIOS;
    private javax.swing.JCheckBox chcWeb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblAndroid;
    private javax.swing.JLabel lblIOS;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JTable tblEstimativaProjeto;
    private javax.swing.JTable tblPrecosPorDiaTrabalho;
    private javax.swing.JTable tblValoresFinais;
    private javax.swing.JTextField txtNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
