/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.projeto.view;

/**
 *
 * @author Cauã
 */
public class VisualizarEstimativaView extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarEstimativaView
     */
    public VisualizarEstimativaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tblValoresFinais = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTaxasExtras = new javax.swing.JTable();
        lblVisualizarEstimativa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionalidadesProjeto = new javax.swing.JTable();
        lblPlataformas = new javax.swing.JLabel();
        txtPlataformas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblValoresFinais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblValoresFinais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblValoresFinais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Valor", null},
                {"+ Taxas Extras", null},
                {"Imposto  Calculado", null},
                {"+ Impostos", null},
                {"Lucro Calculado", null},
                {"Dias", null},
                {"Meses", null},
                {"Preço Final ao Cliente", null},
                {"Média por Mês", null}
            },
            new String [] {
                "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblValoresFinais.setRowHeight(50);
        tblValoresFinais.setShowHorizontalLines(true);
        tblValoresFinais.setShowVerticalLines(true);
        tblValoresFinais.getTableHeader().setResizingAllowed(false);
        tblValoresFinais.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblValoresFinais);
        if (tblValoresFinais.getColumnModel().getColumnCount() > 0) {
            tblValoresFinais.getColumnModel().getColumn(0).setResizable(false);
            tblValoresFinais.getColumnModel().getColumn(1).setResizable(false);
        }

        tblTaxasExtras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblTaxasExtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTaxasExtras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Preço por dia de traballho  -Designer UI/UX", null},
                {"Preço por dia de traballho - Gerência de Projeto", null},
                {"Preço por dia de traballho  - Desenvolvimento", null},
                {"Custo com hardware e instalações físicas.", null},
                {"Custo com softwares.", null},
                {"Custo com riscos.", null},
                {"Custo com garantia.", null},
                {"Fundo de reserva", null},
                {"Outros custos.", null},
                {"Percentual com impostos(%)", null},
                {"Percentual de Lucro desejado (%)", null}
            },
            new String [] {
                "Taxas extras", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTaxasExtras.setRowHeight(50);
        tblTaxasExtras.setShowHorizontalLines(true);
        tblTaxasExtras.setShowVerticalLines(true);
        tblTaxasExtras.getTableHeader().setResizingAllowed(false);
        tblTaxasExtras.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblTaxasExtras);
        if (tblTaxasExtras.getColumnModel().getColumnCount() > 0) {
            tblTaxasExtras.getColumnModel().getColumn(0).setResizable(false);
            tblTaxasExtras.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblTaxasExtras.getColumnModel().getColumn(1).setResizable(false);
            tblTaxasExtras.getColumnModel().getColumn(1).setPreferredWidth(20);
        }

        lblVisualizarEstimativa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVisualizarEstimativa.setText("VISUALIZAR ESTIMATIVA DE PROJETO");

        tblFuncionalidadesProjeto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblFuncionalidadesProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblFuncionalidadesProjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionalidade que o aplicativo terá", "Total de dias", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionalidadesProjeto.setToolTipText("");
        tblFuncionalidadesProjeto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblFuncionalidadesProjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblFuncionalidadesProjeto.setRowHeight(50);
        tblFuncionalidadesProjeto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFuncionalidadesProjeto.setShowHorizontalLines(true);
        tblFuncionalidadesProjeto.setShowVerticalLines(true);
        tblFuncionalidadesProjeto.setSurrendersFocusOnKeystroke(true);
        tblFuncionalidadesProjeto.getTableHeader().setResizingAllowed(false);
        tblFuncionalidadesProjeto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblFuncionalidadesProjeto);
        if (tblFuncionalidadesProjeto.getColumnModel().getColumnCount() > 0) {
            tblFuncionalidadesProjeto.getColumnModel().getColumn(0).setResizable(false);
            tblFuncionalidadesProjeto.getColumnModel().getColumn(0).setPreferredWidth(500);
            tblFuncionalidadesProjeto.getColumnModel().getColumn(1).setResizable(false);
            tblFuncionalidadesProjeto.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblFuncionalidadesProjeto.getColumnModel().getColumn(2).setResizable(false);
            tblFuncionalidadesProjeto.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        lblPlataformas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPlataformas.setText("Plataformas:");

        txtPlataformas.setEditable(false);
        txtPlataformas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVisualizarEstimativa)
                .addGap(623, 623, 623))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlataformas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addGap(0, 50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblVisualizarEstimativa)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlataformas)
                    .addComponent(txtPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarEstimativaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarEstimativaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblPlataformas;
    private javax.swing.JLabel lblVisualizarEstimativa;
    private javax.swing.JTable tblFuncionalidadesProjeto;
    private javax.swing.JTable tblTaxasExtras;
    private javax.swing.JTable tblValoresFinais;
    private javax.swing.JTextField txtPlataformas;
    // End of variables declaration//GEN-END:variables
}
